### ISSUE TITLE
How do combining symbols work?

### ISSUE THREAD

**Issue by Amparose** [adamkiss/alfred-utf#10]
I assumed these were for creating accents like `é` but I can't seem to get it to work and output is `◌́`.

**Comment by adamkiss** [comment]
I don't understand your question - I have no idea how system treats combining characters when standalone, but you can easily do `utf e acute` and first result is `é`:

![CleanShot 2024-11-30 at 13 41 06@2x](https://github.com/user-attachments/assets/9b69e25e-15e1-4901-869e-5938bf1cf5b5)

(note that in the screenshot, the workflow trigger is `u` because that's what I use, it's utf by default)
