### ISSUE TITLE
Great Workflow, but I can't make it work.

### ISSUE THREAD

**Issue by suliveevil** [adamkiss/alfred-utf#2]
Would you please help me out? Thank you very much.

```shell
ERROR: UTF Search[Script Filter] Code 1: Parse error near line 3: no such table: user.usage
```

**Comment by adamkiss** [comment]
Ah, i now realise that i added usage in the main workflow, but don't initialise the user database until after first successful run 🫣

I'll push an update - in the meantime @suliveevil  - try running `utf10` first - it won't return anything, since it hasn't run yet, but that one creates the user database.

**Comment by suliveevil** [comment]
utf10 brings up another error 🤣

`ERROR: UTF Search[Script Filter] Code 1: Parse error near line 3: no such table: main.usage`

**Comment by adamkiss** [comment]
@suliveevil Yes i see it 🫣 regardless, the main workflow should now work

Ill fix this too 🫥

Edit: nevermind. It won't. I'll look into it.

**Comment by suliveevil** [comment]
Thank you very much.🥰

**Comment by adamkiss** [comment]
@suliveevil no problem - I also want my "almost daily used" workflow to be bug free.

This should be now fixed. Please try the ~~2.0.2~~ 2.0.3 version

**Comment by suliveevil** [comment]
It works!
