### ISSUE TITLE
Search Unicode ID

### ISSUE THREAD

**Issue by suliveevil** [adamkiss/alfred-utf#4]
Will alfred-utf support search unicode id?

For example `utf 0027`

**Comment by adamkiss** [comment]
I'm thinking about it. Have you used the old python 2 version? did it support this?

Edit: yes, i think i can think of couple ways of adding it. Would `utf :u:0027` work for you, @suliveevil?

Edit edit: Actually, you can search for unicode id right now, with `utf \\u0027`, or raw query on the hex without leading zeroes, like so: `utf :^27`

**Comment by suliveevil** [comment]
Wow! This blows my mind.

Actually `utf :u0027` works while `utf :u:0027` didn't.

**Comment by adamkiss** [comment]
@suliveevil because `:u:0027` was an idea, for which I'd need to add another column into the database, while `:u0027` search through columns already available - one of which is called "json", and contains a unicode character in the format `\uXXXX` used in many languages - in this case it's `\u0027`, which the sqlite's fts5 algorithm happily matches with search 'u0027' :)

**Comment by suliveevil** [comment]
> sqlite's fts5 algorithm happily matches with search 'u0027'

This is enough for me 😍
